version: '3'
services:
  base:
    build:
      context: .
      dockerfile: Dockerfile
    image: base-image

  mongodb:
    container_name: mongodb
    image: mongo:5.0.10-focal
    ports:
      - "27017:27017"
    restart: always
    command:
      - "--auth"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: abc123456
      wiredTigerCacheSizeGB: 2

  etcd:
    hostname: etcd
    image: bitnami/etcd
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    privileged: true
    ports:
      - "2379:2379"
      - "2380:2380"
    environment:
      - "ALLOW_NONE_AUTHENTICATION=yes"
      
  redis:
    image: redis:6.0.6
    hostname: redis
    ports:
      - "6379:6379"
    restart: always


  # video:
  #   image: base-image
  #   ports:
  #     - "8084:8084"
  #   command: sh -c "cd /app/rpcServer/video && sleep 10 && ./main"
  #   restart: always
  #   depends_on:
  #     - redis
  #     - etcd
  #     - mongodb

  # relation:
  #   image: base-image
  #   ports:
  #     - "8082:8082"
  #   command: sh -c "cd /app/rpcServer/relation && sleep 10 && ./main"
  #   restart: always
  #   depends_on:
  #     - redis
  #     - etcd
  #     - mongodb

  # message:
  #   image: base-image
  #   ports:
  #     - "8083:8083"
  #   command: sh -c "cd /app/rpcServer/message && sleep 10 && ./main"
  #   restart: always
  #   depends_on:
  #     - redis
  #     - etcd
  #     - mongodb 

  # user:
  #   image: base-image
  #   ports:
  #     - "8081:8081"
  #   command: sh -c "cd /app/rpcServer/user && sleep 10 && ./main"
  #   restart: always
  #   depends_on:
  #     - redis
  #     - etcd
  #     - mongodb

  # interaction:
  #   image: base-image
  #   ports:
  #     - "8085:8085"
  #   command: sh -c "cd /app/rpcServer/interaction && sleep 10 && ./main"
  #   restart: always
  #   depends_on:
  #     - redis
  #     - etcd
  #     - mongodb

  # logger:
  #   image: base-image
  #   command: sh -c "cd /app/rpcServer/logger && sleep 10 && ./main"
  #   restart: always
  #   depends_on:
  #     - redis
  #     - etcd
  #     - mongodb

  # http_server:
  #   image: base-image
  #   depends_on:
  #     - video
  #     - relation
  #     - message
  #     - user
  #     - interaction
  #   ports:
  #     - "8080:8080"
  #   command: sh -c "cd /app && sleep 10 && ./main"
  #   restart: always

