version: '3'
services:

  mysql:
    image: mysql
    hostname: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: abc123456
      MYSQL_DATABASE: douyin
    restart: always

  etcd:
    hostname: etcd
    image: bitnami/etcd
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    privileged: true
    ports:
      - "2379:2379"
      - "2380:2380"
    environment:
      - "ALLOW_NONE_AUTHENTICATION=yes"
      
  redis:
    image: redis
    hostname: redis
    ports:
      - "6379:6379"
    restart: always


  video:
    depends_on:
      - mysql
      - etcd
      - redis
    image: 15150276667/douyin
    ports:
      - "8084:8084"
    command: sh -c "cd /app/rpcServer/video && ./main"
    restart: always
    
  relation:
    depends_on:
      - mysql
      - etcd
      - redis
    image: 15150276667/douyin
    ports:
      - "8082:8082"
    command: sh -c "cd /app/rpcServer/relation && ./main"
    restart: always

  message:
    depends_on:
      - mysql
      - etcd
      - redis
    image: 15150276667/douyin
    ports:
      - "8083:8083"
    command: sh -c "cd /app/rpcServer/message && ./main"
    restart: always

  user:
    depends_on:
      - mysql
      - etcd
      - redis
    image: 15150276667/douyin
    ports:
      - "8081:8081"
    command: sh -c "cd /app/rpcServer/user && ./main"
    restart: always
  
  interaction:
    depends_on:
      - mysql
      - etcd
    image: 15150276667/douyin
    ports:
      - "8085:8085"
    command: sh -c "cd /app/rpcServer/interaction && ./main"
    restart: always

  http_server:
    depends_on:

      - message
      - interaction
      - user
      - relation
      - video
    image: 15150276667/douyin
    ports:
      - "8080:8080"
    command: sh -c "cd /app && ./main"
    restart: always