definitions:
  message.MessageActionRequest:
    properties:
      action_type:
        type: integer
      content:
        type: string
      to_user_id:
        type: integer
      token:
        type: string
    type: object
info:
  contact: {}
paths:
  /douyin/message/action/:
    post:
      consumes:
      - application/json
      description: 登录用户对消息的相关操作，目前只支持消息发送
      parameters:
      - description: Message Action Params
        in: body
        name: token
        required: true
        schema:
          $ref: '#/definitions/message.MessageActionRequest'
      produces:
      - application/json
      tags:
      - example
  /douyin/publish/list/:
    get:
      consumes:
      - application/json
      description: 获取用户发表的视频列表
      parameters:
      - in: query
        name: token
        type: string
      - in: query
        name: user_id
        type: integer
      produces:
      - application/json
      tags:
      - 视频接口
swagger: "2.0"
