definitions:
  message.MessageActionRequest:
    properties:
      action_type:
        type: integer
      content:
        type: string
      to_user_id:
        type: integer
      token:
        type: string
    type: object
  video.PublishListRequest:
    properties:
      token:
        type: string
      user_id:
        type: integer
    type: object
info:
  contact: {}
paths:
  /douyin/message/action/:
    post:
      consumes:
      - application/json
      description: 登录用户对消息的相关操作，目前只支持消息发送
      parameters:
      - description: Message Action Params
        in: body
        name: token
        required: true
        schema:
          $ref: '#/definitions/message.MessageActionRequest'
      produces:
      - application/json
      tags:
      - example
  /douyin/publish/action/:
    post:
      consumes:
      - application/json
      description: 视频投稿
      parameters:
      - in: query
        items:
          type: integer
        name: data
        type: array
      - in: query
        name: title
        type: string
      - in: query
        name: token
        type: string
      produces:
      - application/json
      tags:
      - 视频接口
  /douyin/publish/list/:
    get:
      consumes:
      - application/json
      description: 获取用户发表的视频列表
      parameters:
      - description: body
        in: body
        name: token
        required: true
        schema:
          $ref: '#/definitions/video.PublishListRequest'
      produces:
      - application/json
      tags:
      - 视频接口
swagger: "2.0"
