definitions:
  message.MessageActionRequest:
    properties:
      action_type:
        type: integer
      content:
        type: string
      to_user_id:
        type: integer
      token:
        type: string
    type: object
info:
  contact: {}
paths:
  /douyin/message/action/:
    post:
      consumes:
      - application/json
      description: 登录用户对消息的相关操作，目前只支持消息发送
      parameters:
      - description: token
        in: body
        name: token
        required: true
        schema:
          $ref: '#/definitions/message.MessageActionRequest'
      produces:
      - application/json
      responses: {}
      summary: 消息操作
      tags:
      - example
swagger: "2.0"
